# Generated by Django 5.1.6 on 2025-03-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/replies/'),
        ),
    ]
