# Generated by Django 5.1.6 on 2025-03-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_reply_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
