# Generated by Django 5.1.6 on 2025-03-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_alter_email_attachment_alter_reply_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='attachment',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Dashboard.email')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Dashboard.reply')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('email__isnull', False), ('reply__isnull', False), _connector='OR'), name='attachment_must_belong_to_email_or_reply')],
            },
        ),
    ]
