# Generated by Django 5.1.6 on 2025-04-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_remove_email_attachment_remove_reply_attachment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
