# Generated by Django 5.1.6 on 2025-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkListing', '0002_remove_project_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applications_open',
            field=models.BooleanField(default=True),
        ),
    ]
