# Generated by Django 5.1.6 on 2025-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkListing', '0003_project_applications_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='submission_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
