# Generated by Django 5.1.6 on 2025-03-05 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkListing', '0004_projectrequest_submission_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequest',
            name='submission_url',
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_url', models.URLField(blank=True, null=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='WorkListing.projectrequest')),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'organizational'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project_request',)},
            },
        ),
    ]
