# Generated by Django 5.1.6 on 2025-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkListing', '0005_remove_projectrequest_submission_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True),
        ),
    ]
