# Generated by Django 4.2.18 on 2025-02-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_userprofile_cover_image_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('skills_gained', models.ManyToManyField(related_name='certifications', to='Users.skill')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='Users.userprofile')),
            ],
        ),
    ]
