# Generated by Django 4.2.18 on 2025-02-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
