# Generated by Django 5.1.6 on 2025-02-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_chatgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGroup',
        ),
    ]
