# Generated by Django 5.1.6 on 2025-03-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to='Users.userprofile'),
        ),
    ]
