# Generated by Django 5.1.6 on 2025-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_post_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('normal', 'Normal Post'), ('blog', 'Blog'), ('whitepaper', 'Whitepaper'), ('insight', 'Insight')], default='normal', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
