# Generated by Django 5.1.6 on 2025-03-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='business_nature',
            field=models.CharField(choices=[('PROD', 'Product-based'), ('SERV', 'Service-based'), ('HYBRID', 'Hybrid'), ('PROFESSIONAL', 'Professional')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=models.CharField(choices=[('B2B', 'Business-to-Business'), ('B2C', 'Business-to-Consumer'), ('B2G', 'Business-to-Government')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='education',
            field=models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'Ph.D')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry_type',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('FIN', 'Finance'), ('EDU', 'Education'), ('HLTH', 'Healthcare'), ('MFG', 'Manufacturing')], max_length=100),
        ),
    ]
