# Generated by Django 5.1.6 on 2025-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_alter_organization_business_nature_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
