# Generated by Django 5.1.6 on 2025-03-28 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_delete_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(choices=[('IT', 'Information Technology'), ('FIN', 'Finance'), ('EDU', 'Education'), ('HLTH', 'Healthcare'), ('MFG', 'Manufacturing')], max_length=100)),
                ('organization_name', models.CharField(max_length=200)),
                ('total_employees', models.IntegerField()),
                ('description', models.TextField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_number', models.CharField(max_length=15)),
                ('start_year', models.IntegerField()),
                ('business_type', models.CharField(choices=[('B2B', 'Business-to-Business'), ('B2C', 'Business-to-Consumer'), ('B2G', 'Business-to-Government')], max_length=100)),
                ('business_nature', models.CharField(choices=[('PROD', 'Product-based'), ('SERV', 'Service-based'), ('HYBRID', 'Hybrid'), ('PROFESSIONAL', 'Professional')], max_length=100)),
                ('challenges', models.TextField()),
                ('digital_assets', models.TextField()),
                ('desired_assets', models.TextField()),
                ('skills', models.TextField()),
                ('wish_to_expand', models.BooleanField()),
                ('locations', models.TextField()),
                ('education', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'Ph.D')], max_length=50)),
                ('website_link', models.URLField()),
                ('open_positions', models.TextField()),
                ('willing_to_collaborate', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
