# Generated by Django 5.1.6 on 2025-04-01 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='Users.degree')),
            ],
        ),
        migrations.CreateModel(
            name='User_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
                ('current_occupation', models.CharField(max_length=100)),
                ('current_organization', models.CharField(max_length=200)),
                ('top_skills', models.JSONField(default=list)),
                ('is_fresher', models.BooleanField(default=False)),
                ('on_career_break', models.BooleanField(default=False)),
                ('desired_job_role', models.CharField(max_length=100)),
                ('specific_position', models.CharField(max_length=100)),
                ('career_goal_skills', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('looking_for_career_switch', models.BooleanField(default=False)),
                ('willing_to_take_projects', models.BooleanField(default=False)),
                ('interested_in_new_course', models.BooleanField(default=False)),
                ('portfolio_link', models.URLField()),
                ('ideal_organization', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highest_degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.degree')),
                ('preferred_industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.industry')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Professional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
