# Generated by Django 5.1.6 on 2025-04-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_degree_industry_specialization_user_form'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user_profile', 'content_type', 'content_id')},
        ),
    ]
