# Generated by Django 5.1.6 on 2025-04-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
    ]
