# Generated by Django 5.1.6 on 2025-04-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user_profile', 'content_type', 'content_id')},
        ),
    ]
