# Generated by Django 5.2 on 2025-04-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0029_newmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Deactivate', 'Deactivate'), ('Suspend', 'Suspend')], default='Open', max_length=20),
        ),
    ]
