<<<<<<< Updated upstream
# Generated by Django 5.2 on 2025-04-15 10:20
=======
# Generated by Django 5.1.8 on 2025-04-16 09:43
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_customuser_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
