# Generated by Django 5.1.8 on 2025-04-19 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0033_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
