# Generated by Django 4.2.18 on 2025-02-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('overview', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails/')),
                ('featured_video', models.FileField(blank=True, null=True, upload_to='featured_videos/')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('duration', models.DurationField()),
                ('prerequisites', models.TextField()),
                ('skills', models.TextField(blank=True, help_text='List of skills covered in the course')),
                ('category', models.CharField(choices=[('development', 'Development'), ('business', 'Business'), ('finance', 'Finance & Accounting'), ('it_software', 'IT & Software'), ('office_productivity', 'Office Productivity'), ('personal_development', 'Personal Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('lifestyle', 'Lifestyle'), ('photography_video', 'Photography & Video'), ('health_fitness', 'Health & Fitness'), ('music', 'Music'), ('teaching_academics', 'Teaching & Academics')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'instructor')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='lesson_videos/')),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='Training.course')),
            ],
        ),
    ]
