# Generated by Django 4.2.18 on 2025-02-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0003_lessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
    ]
