# Generated by Django 5.1.6 on 2025-03-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalAssets', '0002_delete_insight'),
        ('Users', '0020_post_content_id_post_content_type_alter_post_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('sources', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=10)),
                ('categories', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='Users.userprofile')),
            ],
        ),
    ]
