# Generated by Django 5.1.6 on 2025-03-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalAssets', '0003_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whitepaper',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
