# Generated by Django 5.1.6 on 2025-03-18 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalAssets', '0004_blog_is_draft_insight_is_draft_whitepaper_is_draft'),
        ('Users', '0020_post_content_id_post_content_type_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitepaper',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userprofile'),
        ),
    ]
