# Generated by Django 5.1.6 on 2025-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalAssets', '0005_whitepaper_content_alter_whitepaper_summary_and_more'),
        ('Users', '0021_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitepaper',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitepapers', to='Users.userprofile'),
        ),
    ]
